import { Anime } from "../types";

export const dummyAnimeList: Anime[] = [
  {
    id: 11061,
    name: "Hunter x Hunter (2011)",
    synopsis: "Gon Freecss sets out on a journey to become a Hunter and find his missing father.",
    malUrl: "https://myanimelist.net/anime/11061/Hunter_x_Hunter_2011",
    imageUrl: "https://cdn.myanimelist.net/images/anime/1537/145325.jpg",
    genres: [1, 2, 3, 4],
    staff: ["Yoshihiro Togashi", "Hiroshi Koujina", "Jun Maekawa"],
    companies: ["Madhouse"],
    malScore: 9.0,
    members: 2500000,
    airingDate: { start: new Date("2011-10-02"), end: new Date("2014-09-24") },
    status: "Finished Airing",
    type: "TV",
    episodeCount: 148,
  },
  {
    id: 9253,
    name: "Steins;Gate",
    synopsis: "A self-proclaimed mad scientist accidentally discovers time travel and gets caught in a dangerous conspiracy.",
    malUrl: "https://myanimelist.net/anime/9253/Steins_Gate",
    imageUrl: "https://cdn.myanimelist.net/images/anime/5/73199.jpg",
    genres: [2, 3, 4, 5, 6],
    staff: ["Hiroshi Hamasaki", "Takuya Satou", "Jukki Hanada"],
    companies: ["White Fox"],
    malScore: 9.1,
    members: 2200000,
    airingDate: { start: new Date("2011-04-06"), end: new Date("2011-09-14") },
    status: "Finished Airing",
    type: "TV",
    episodeCount: 24,
  },
  {
    id: 30276,
    name: "One Punch Man",
    synopsis: "Saitama, a hero for fun, seeks a challenge after becoming too strong and defeating every enemy with a single punch.",
    malUrl: "https://myanimelist.net/anime/30276/One_Punch_Man",
    imageUrl: "https://cdn.myanimelist.net/images/anime/12/76049.jpg",
    genres: [8, 12, 14, 17, 11],
    staff: ["Shingo Natsume", "Tomohiro Suzuki"],
    companies: ["Madhouse"],
    malScore: 8.5,
    members: 2300000,
    airingDate: { start: new Date("2015-10-05"), end: new Date("2015-12-21") },
    status: "Finished Airing",
    type: "TV",
    episodeCount: 12,
  },
  {
    id: 1535,
    name: "Death Note",
    synopsis: "A high school student discovers a notebook that kills anyone whose name is written in it.",
    malUrl: "https://myanimelist.net/anime/1535/Death_Note",
    imageUrl: "https://cdn.myanimelist.net/images/anime/9/9453.jpg",
    genres: [2, 3, 7, 8],
    staff: ["Tsugumi Ohba", "Takeshi Obata", "Tetsuro Araki"],
    companies: ["Madhouse"],
    malScore: 8.6,
    members: 3000000,
    airingDate: { start: new Date("2006-10-04"), end: new Date("2007-06-27") },
    status: "Finished Airing",
    type: "TV",
    episodeCount: 37,
  },
  {
    id: 16498,
    name: "Attack on Titan",
    synopsis: "Humanity fights for survival against man-eating giants called Titans.",
    malUrl: "https://myanimelist.net/anime/16498/Shingeki_no_Kyojin",
    imageUrl: "https://cdn.myanimelist.net/images/anime/10/47347.jpg",
    genres: [1, 2, 3, 8],
    staff: ["Hajime Isayama", "Tetsuro Araki", "Yasuko Kobayashi"],
    companies: ["Wit Studio"],
    malScore: 8.5,
    members: 2800000,
    airingDate: { start: new Date("2013-04-07"), end: new Date("2013-09-29") },
    status: "Finished Airing",
    type: "TV",
    episodeCount: 25,
  },
  {
    id: 5114,
    name: "Fullmetal Alchemist: Brotherhood",
    synopsis: "Two brothers search for the Philosopher's Stone to restore their bodies after a failed alchemical experiment.",
    malUrl: "https://myanimelist.net/anime/5114/Fullmetal_Alchemist__Brotherhood",
    imageUrl: "https://cdn.myanimelist.net/images/anime/1223/96541.jpg",
    genres: [1, 2, 3, 8, 9],
    staff: ["Hiromu Arakawa", "Yasuhiro Irie", "Hiroshi Ōnogi"],
    companies: ["Bones"],
    malScore: 9.1,
    members: 2700000,
    airingDate: { start: new Date("2009-04-05"), end: new Date("2010-07-04") },
    status: "Finished Airing",
    type: "TV",
    episodeCount: 64,
  },
  {
    id: 38524,
    name: "Shingeki no Kyojin: The Final Season",
    synopsis: "The continuation of Attack on Titan, as the truth about the world unfolds.",
    malUrl: "https://myanimelist.net/anime/38524/Shingeki_no_Kyojin__The_Final_Season",
    imageUrl: "https://cdn.myanimelist.net/images/anime/1000/110531.jpg",
    genres: [1, 2, 3, 8],
    staff: ["Hajime Isayama", "Yuichiro Hayashi", "Hiroshi Seko"],
    companies: ["MAPPA"],
    malScore: 8.9,
    members: 1800000,
    airingDate: { start: new Date("2020-12-07"), end: new Date("2025-03-04") },
    status: "Currently Airing",
    type: "TV",
    episodeCount: 16,
  },
];
